[project]
name = "ragyt"
version = "0.1.0"
description = "AskYoutube RAG Backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.135.2",
    "mistralai>=2.1.3",
    "pinecone>=7.3.0",
    "pydantic>=2.10.0",
    "pymongo>=4.16.0",
    "dnspython>=2.8.0",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.42.0",
    "youtube-transcript-api>=1.2.4",
]

